### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [alexeyzab/article-date-extractor#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by alexeyzab** [comment]
Hey there! 

Sorry for getting back to you so late, somehow I wasn't watching this repository so I didn't get a notification. I've removed `rustc-serialize` and replace it with `serde_json`. No additional functionality was needed.

Thank you for reaching out and letting me know!
